name: apiverve_daylightduration
description: Daylight Duration Calculator computes sunrise, sunset times, and total daylight hours for any geographic location and date using astronomical algorithms.
version: 1.1.14
homepage: https://apiverve.com/marketplace/daylightduration?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/daylightduration-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
