// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DaylightDurationCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty("condition")]
        public string Condition { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("sunrise")]
        public DateTimeOffset Sunrise { get; set; }

        [JsonProperty("sunset")]
        public string Sunset { get; set; }

        [JsonProperty("daylight_duration")]
        public DaylightDuration DaylightDuration { get; set; }

        [JsonProperty("day_of_year")]
        public long DayOfYear { get; set; }

        [JsonProperty("is_valid")]
        public bool IsValid { get; set; }
    }

    public partial class DaylightDuration
    {
        [JsonProperty("total_minutes")]
        public double TotalMinutes { get; set; }

        [JsonProperty("hours")]
        public long Hours { get; set; }

        [JsonProperty("minutes")]
        public long Minutes { get; set; }

        [JsonProperty("formatted")]
        public DateTimeOffset Formatted { get; set; }
    }

    public partial class Location
    {
        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }
    }
}
